name: Render AsciiDoc to various formats
run-name: ${{ github.actor }} triggered a rendering on branch ${{ github.ref }}...
on: [push]
jobs:
  Render-AsciiDoc_separate_files:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Render the files
        uses: ./.github/render-action
      - name: List the generated files
        run: |
          ls ./generated
      - name: Upload built Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}/generated
      - run: echo "ğŸ This job's status is ${{ job.status }}."
